### ISSUE TITLE
feat: add length of highlighting, i.e. CursorLine

### ISSUE THREAD

**Issue by Fin-NewWin** [atusy/tsnode-marker.nvim#4]

**Comment by atusy** [comment]
Would you describe more about your request?
I do not understand...

**Comment by Fin-NewWin** [comment]
I was referring to the horizontal highlighting of the tsnode

![image](https://user-images.githubusercontent.com/56209439/220487475-729bfab1-0333-4ad9-83aa-79f899a455f4.png)

There is a vertical bar to to the right, I was wondering if there is a way to stop the highlighting to that bar without affecting the rest.

**Comment by atusy** [comment]
I see. So you mean colorcolumn rather than CursorLine.

Length of `nvim_buf_set_extmark()` has two choice

1. up to the number of characters in the line
2. entire line

and we cannot stop the extmark in between.

Also, the 1st choice is not adequate as blank lines won't be highlighted.

<img width="142" alt="image" src="https://user-images.githubusercontent.com/30277794/220492236-2a2dbdeb-ae48-4c47-b7c5-dec5266ed488.png">

**Comment by atusy** [comment]
Do you have any suggestions?
I would be happy to review PR.

**Comment by Fin-NewWin** [comment]
No, thank you for the for the fast response.
